# Generated by Django 2.0.4 on 2018-06-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Homes',
        ),
    ]
